<aside class="left-side sidebar-offcanvas">
	<section class="sidebar">
		<?php if ($this->session->has('identity')) { ?>
		<div class="user-panel">
			<div class="pull-left image">
				<img src="/img/avatar3.png" class="img-circle" alt="User Image" />
			</div>
			<div class="pull-left info">
				<p>Hello, <?= $this->session->get('showname') ?></p>

				<a href="#"><i class="fa fa-circle text-success"></i> Online</a>
			</div>
		</div>
		<?php } ?>
		<form action="#" method="get" class="sidebar-form">
			<div class="input-group">
				<input type="text" name="q" class="form-control" placeholder="Search..."/>
				<span class="input-group-btn">
					<button type='submit' name='seach' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
				</span>
			</div>
		</form>
		<ul class="sidebar-menu">
			<li class="active">
				<a href="#">
					<i class="fa fa-dashboard"></i> <span>导航</span>
				</a>
			</li>
			<li class="treeview">
				<a href="#">
					<i class="fa fa-bar-chart-o"></i>
					<span>账户中心</span>
					<i class="fa fa-angle-left pull-right"></i>
				</a>
				<ul class="treeview-menu">
					<li><a href="#"><i class="fa fa-angle-double-right"></i> 基本资料</a></li>
					<li><a href="#"><i class="fa fa-angle-double-right"></i> 安全信息</a></li>
					<li><a href="#"><i class="fa fa-angle-double-right"></i> 修改密码</a></li>
				</ul>
			</li>
			<li>
				<a href="#">
					<i class="fa fa-envelope"></i> <span>我的订单</span>
					<small class="badge pull-right bg-yellow">12</small>
				</a>
			</li>
			<li class="treeview">
				<a href="#">
					<i class="fa fa-laptop"></i>
					<span>商品分类</span>
					<i class="fa fa-angle-left pull-right"></i>
				</a>
				<ul class="treeview-menu">
					<li><a href="#"><i class="fa fa-angle-double-right"></i> 服饰</a></li>
					<li><a href="#"><i class="fa fa-angle-double-right"></i> 珠宝</a></li>
					<li><a href="#"><i class="fa fa-angle-double-right"></i> 百货</a></li>
				</ul>
			</li>
		</ul>
	</section>
</aside>